/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 Beetle.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Beetle.gltf')
  return (
    <group {...props} dispose={null} scale={15}>
      <group rotation={[Math.PI, 0.008, -Math.PI / 2]} scale={[0.074, 0.03, 0.074]}>
        <mesh geometry={nodes.Cylinder001.geometry} material={materials.bolt} />
        <mesh geometry={nodes.Cylinder001_1.geometry} material={materials.wood} />
        <mesh geometry={nodes.Cylinder001_2.geometry} material={materials.metal} />
        <mesh geometry={nodes.Cylinder001_3.geometry} material={materials.white} />
        <mesh geometry={nodes.Cylinder001_4.geometry} material={materials.black} />
        <mesh geometry={nodes.Cylinder001_5.geometry} material={materials.Beetle} />
      </group>
    </group>
  )
}

useGLTF.preload('/Beetle.gltf')
