/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 Dali.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Dali.gltf')
  return (
    <group {...props} dispose={null} scale={15}>
      <group rotation={[1.689, 0, 0]} scale={[8, 4.89, 7.999]}>
        <mesh geometry={nodes.Plane007_1.geometry} material={materials['white.001']} />
        <mesh geometry={nodes.Plane007_2.geometry} material={materials.black} />
        <mesh geometry={nodes.Plane007_3.geometry} material={materials.Dali} />
      </group>
    </group>
  )
}

useGLTF.preload('/Dali.gltf')
