/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 Flower.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Flower.gltf')
  return (
    <group {...props} dispose={null} scale={15}>
      <group rotation={[1.689, 0, 0]} scale={[2.5, 1.665, 2.5]}>
        <mesh geometry={nodes.Plane012_1.geometry} material={materials['white.001']} />
        <mesh geometry={nodes.Plane012_2.geometry} material={materials.Material} />
      </group>
    </group>
  )
}

useGLTF.preload('/Flower.gltf')
