/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 Joker.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Joker.gltf')
  return (
    <group {...props} dispose={null} scale={15}>
      <group rotation={[1.689, 0, 0]} scale={[3.344, 4.89, 4.826]}>
        <mesh geometry={nodes.Plane004_1.geometry} material={materials['white.001']} />
        <mesh geometry={nodes.Plane004_2.geometry} material={materials.Joker} />
        <mesh geometry={nodes.Plane004_3.geometry} material={materials.black} />
      </group>
    </group>
  )
}

useGLTF.preload('/Joker.gltf')
