/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 Norman.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Norman.gltf')
  return (
    <group {...props} dispose={null} scale={15}>
      <group rotation={[1.689, 0, 0]} scale={[7, 4.89, 10.499]}>
        <mesh geometry={nodes.Plane009_1.geometry} material={materials['white.001']} />
        <mesh geometry={nodes.Plane009_2.geometry} material={materials.black} />
        <mesh geometry={nodes.Plane009_3.geometry} material={materials.Norman} />
      </group>
    </group>
  )
}

useGLTF.preload('/Norman.gltf')
