/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 ThreeWomen.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/ThreeWomen.gltf')
  return (
    <group {...props} dispose={null} scale={15}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={10}>
        <mesh geometry={nodes.Easel_01a002__0001_1.geometry} material={materials['Scene_-_Root']} />
        <mesh geometry={nodes.Easel_01a002__0001_2.geometry} material={materials['3Women']} />
        <mesh geometry={nodes.Easel_01a002__0001_3.geometry} material={materials.Beetle} />
      </group>
    </group>
  )
}

useGLTF.preload('/ThreeWomen.gltf')
